FROM python:3.14-slim


# Instalación de UV
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Establecer directorio de trabajo del contenedor y donde se guardara todo
WORKDIR /app

# copiar pyproject
COPY pyproject.toml uv.lock ./

# Instalar
RUN uv sync --frozen

#Traer todo
COPY . .

#exponer el puerto 8000
EXPOSE 8000

#Ejecutar fastapi mediante uvicorn en el host 0.0.0.0
CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

#Ejecución:
#docker build -t backend-tickets:latest .
#docker run -p 8000:8000 --env-file .env backend-tickets
