services:
  backend:
    container_name: backend-tickets
    build:
      context: ./backend #carpeta del proyecto
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - chaucherapp_net #Red local
  
  frotend:
    container_name: frontend-ticket
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    networks:
      - chaucherapp_net
    depends_on:
      - backend #Ejecuta primero el backend
  
networks:
  chaucherapp_net:
    driver: bridge
  
#Para ejecutar:
#docker compose up --build